# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taps_oan', '0008_yelpsearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='title',
            new_name='name',
        ),
    ]
