# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taps_oan', '0009_auto_20170304_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YelpSearch',
        ),
    ]
